site_name: My Documentation Site

# You can also specify a description or other metadata.
site_description: A simple static site for your documentation.
site_author: Your Name

# Navigation menu
nav:
  - Home: index.md
  - Appetite: 1/appetite.md
  - Interpreter: 2/interpreter.md
  - Introduction: 3/introduction.md
  - Control Flow: 4/controlflow.md
  - Data Structures: 5/datastructures.md
  - Modules: 6/modules.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md

# The theme used to render the docs
theme:
  name: 'material'

